### ISSUE TITLE
moe-sdk-1.2.3.pom not available when opening project in AndroidStudio

### ISSUE THREAD

**Issue by AlexandreHerbreteau** [libgdx/gdx-pay-example#5]
A problem occurred evaluating root project 'gdx-pay-example'.
> Failed to apply plugin [id 'moe']
   > Could not resolve all files for configuration ':ios-moe:moeMavenSDK'.
      > Could not resolve org.multi-os-engine:moe-sdk:1.2.3.
        Required by:
            project :ios-moe
         > Could not resolve org.multi-os-engine:moe-sdk:1.2.3.
            > Could not get resource 'https://dl.bintray.com/multi-os-engine/maven/org/multi-os-engine/moe-sdk/1.2.3/moe-sdk-1.2.3.pom'.
               > Could not GET 'https://dl.bintray.com/multi-os-engine/maven/org/multi-os-engine/moe-sdk/1.2.3/moe-sdk-1.2.3.pom'.
                  > Remote host closed connection during handshake

**Comment by MrStahlfelge** [comment]
I have upgraded the project

**Comment by AlexandreHerbreteau** [comment]
Thanks, this works now.
